# Generated by Django 2.0.1 on 2018-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180220_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_type',
            field=models.SmallIntegerField(choices=[(0, 'alias'), (1, 'absolute_url')], default=0),
        ),
    ]
